### ISSUE TITLE
Windows 11: cannot run with Java JRE 8 (32 bit)

### ISSUE THREAD

**Issue by RalfPeter** [peregin/gps-overlay-on-video#222]
Hi,
i have java 8 (401 x32) installed on my windows 11 machine. When i start the newest version i get the following error messages:

D:\test\sample>"C:\Program Files (x86)\Java\jre-1.8\bin\java" -jar "c:\users\ralf\meine tools\gps-overlay-on-video.jar"
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
        at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
        at java.util.ServiceLoader$1.next(Unknown Source)
        at org.slf4j.LoggerFactory.safelyInstantiate(LoggerFactory.java:149)
        at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:130)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:191)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:183)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:486)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:472)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:421)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:447)
        at peregin.gpv.util.Logging.log(Logging.scala:10)
        at peregin.gpv.util.Logging.log$(Logging.scala:10)
        at peregin.gpv.GpsOverlayApp$.log$lzycompute(GpsOverlayApp.scala:22)
        at peregin.gpv.GpsOverlayApp$.log(GpsOverlayApp.scala:22)
        at peregin.gpv.GpsOverlayApp$.<clinit>(GpsOverlayApp.scala:26)
        at peregin.gpv.GpsOverlayApp.main(GpsOverlayApp.scala)

I think i need a newer java runtime? Which version should i download?

**Comment by kvr000** [comment]
Minimum Java 11 is required but anything newer should work too.  And I believe only 64-bit video libraries are provided.
