### ISSUE TITLE
Running on linux

### ISSUE THREAD

**Issue by spackonaut** [peregin/gps-overlay-on-video#33]
Is it possible to run it on linux? I have arch linux with sbt 1:0.13.9-1.

I get this error (I don't have a clue about java or scala):

[info] Running peregin.gpv.App 
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug]         /run/media/user/data/gps-overlay-on-video-1.0.0/target/scala-2.10/classes
[debug]         /home/user/.sbt/boot/scala-2.10.4/lib/scala-library.jar
[debug]         /home/user/.ivy2/cache/org.scala-lang/scala-swing/jars/scala-swing-2.10.4.jar
[debug]         /home/user/.ivy2/cache/com.typesafe.akka/akka-actor_2.10/jars/akka-actor_2.10-2.3.7.jar
[debug]         /home/user/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar
[debug]         /home/user/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.10/jars/akka-slf4j_2.10-2.3.7.jar
[debug]         /home/user/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.5.jar
[debug]         /home/user/.ivy2/cache/org.swinglabs/swingx-core/jars/swingx-core-1.6.2-2.jar
[debug]         /home/user/.ivy2/cache/org.swinglabs/swingx-ws/jars/swingx-ws-1.0.jar
[debug]         /home/user/.ivy2/cache/jdom/jdom/jars/jdom-1.0.jar
[debug]         /home/user/.ivy2/cache/commons-httpclient/commons-httpclient/jars/commons-httpclient-3.0.1.jar
[debug]         /home/user/.ivy2/cache/junit/junit/jars/junit-3.8.1.jar
[debug]         /home/user/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.jar
[debug]         /home/user/.ivy2/cache/log4j/log4j/jars/log4j-1.2.12.jar
[debug]         /home/user/.ivy2/cache/logkit/logkit/jars/logkit-1.0.1.jar
[debug]         /home/user/.ivy2/cache/avalon-framework/avalon-framework/jars/avalon-framework-4.1.3.jar
[debug]         /home/user/.ivy2/cache/javax.servlet/servlet-api/jars/servlet-api-2.3.jar
[debug]         /home/user/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.3.jar
[debug]         /home/user/.ivy2/cache/net.sf.json-lib/json-lib/jars/json-lib-0.9.jar
[debug]         /home/user/.ivy2/cache/commons-beanutils/commons-beanutils/jars/commons-beanutils-1.7.0.jar
[debug]         /home/user/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.2.jar
[debug]         /home/user/.ivy2/cache/xom/xom/jars/xom-1.1.jar
[debug]         /home/user/.ivy2/cache/xerces/xmlParserAPIs/jars/xmlParserAPIs-2.6.2.jar
[debug]         /home/user/.ivy2/cache/xalan/xalan/jars/xalan-2.7.0.jar
[debug]         /home/user/.ivy2/cache/jaxen/jaxen/jars/jaxen-1.1-beta-8.jar
[debug]         /home/user/.ivy2/cache/dom4j/dom4j/jars/dom4j-1.6.1.jar
[debug]         /home/user/.ivy2/cache/net.sf.ezmorph/ezmorph/jars/ezmorph-0.8.1.jar
[debug]         /home/user/.ivy2/cache/xerces/xercesImpl/jars/xercesImpl-2.8.1.jar
[debug]         /home/user/.ivy2/cache/jtidy/jtidy/jars/jtidy-4aug2000r7-dev.jar
[debug]         /home/user/.ivy2/cache/rome/rome/jars/rome-0.8.jar
[debug]         /home/user/.ivy2/cache/com.jgoodies/looks/jars/looks-2.2.2.jar
[debug]         /home/user/.ivy2/cache/com.jgoodies/jgoodies-common/jars/jgoodies-common-1.7.0.jar
[debug]         /home/user/.ivy2/cache/com.miglayout/miglayout/jars/miglayout-3.7.4.jar
[debug]         /home/user/.ivy2/cache/xuggle/xuggle-xuggler/jars/xuggle-xuggler-5.4.jar
[debug]         /home/user/.ivy2/cache/commons-cli/commons-cli/jars/commons-cli-1.1.jar
[debug]         /home/user/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.0.0.jar
[debug]         /home/user/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.0.jar
[debug]         /home/user/.ivy2/cache/org.json4s/json4s-native_2.10/jars/json4s-native_2.10-3.2.11.jar
[debug]         /home/user/.ivy2/cache/org.json4s/json4s-core_2.10/jars/json4s-core_2.10-3.2.11.jar
[debug]         /home/user/.ivy2/cache/org.json4s/json4s-ast_2.10/jars/json4s-ast_2.10-3.2.11.jar
[debug]         /home/user/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.6.jar
[debug]         /home/user/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.10.0.jar
[debug]         /home/user/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.10.0.jar
[debug]         /home/user/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.10.0.jar
[debug]         /home/user/.ivy2/cache/org.json4s/json4s-jackson_2.10/jars/json4s-jackson_2.10-3.2.11.jar
[debug]         /home/user/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.3.1.jar
[debug]         /home/user/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.3.0.jar
[debug]         /home/user/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.3.1.jar
[debug]         /home/user/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.5.jar
[debug]         /home/user/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.7.jar
[debug] Waiting for thread run-main-0 to terminate.
[error] (run-main-0) java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at peregin.gpv.App.main(App.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sbt.Run.invokeMain(Run.scala:72)
        at sbt.Run.run0(Run.scala:65)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
        at sbt.Logger$$anon$4.apply(Logger.scala:90)
        at sbt.TrapExit$App.run(TrapExit.scala:244)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: input == null!
        at javax.imageio.ImageIO.read(ImageIO.java:1348)
        at peregin.gpv.util.Io$.loadImage(Io.scala:19)
        at peregin.gpv.util.Io$.loadIcon(Io.scala:21)
        at peregin.gpv.gui.StartStopButton.<init>(StartStopButton.scala:11)
        at peregin.gpv.gui.VideoPanel.<init>(VideoPanel.scala:27)
        at peregin.gpv.App$$anon$1.<init>(App.scala:28)
        at peregin.gpv.App$.<init>(App.scala:28)
        at peregin.gpv.App$.<clinit>(App.scala)
        at peregin.gpv.App.main(App.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sbt.Run.invokeMain(Run.scala:72)
        at sbt.Run.run0(Run.scala:65)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
        at sbt.Logger$$anon$4.apply(Logger.scala:90)
        at sbt.TrapExit$App.run(TrapExit.scala:244)
        at java.lang.Thread.run(Thread.java:745)
[debug]         Thread run-main-0 exited.
[debug] Interrupting remaining threads (should be all daemons).
[debug] Not interrupting system thread Thread[AWT-XAWT,6,system]
[debug] Not interrupting system thread Thread[XToolkt-Shutdown-Thread,5,system]
[debug] Not interrupting system thread Thread[Java2D Disposer,10,system]
[debug] Sandboxed run complete..
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1708)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1708)
        at scala.Option.foreach(Option.scala:236)
        at sbt.BuildCommon$class.toError(Defaults.scala:1708)
        at sbt.Defaults$.toError(Defaults.scala:35)
        at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defau
        at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defau
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scal
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (compile:run) Nonzero exit code: 1

**Comment by peregin** [comment]
Yes, it is possible, I'm running it on a Mac for example.
Based on the stack trace looks like at initialisation time some images - used for the icons - wer not found.
Let me take look...

**Comment by peregin** [comment]
just pushed a quick workaround, please try it again

**Comment by spackonaut** [comment]
Thanks a lot, it is running now.
