### ISSUE TITLE
problem after loading a video

### ISSUE THREAD

**Issue by valgit** [peregin/gps-overlay-on-video#40]
Under Fedora 28, with jar from latest release (telemetry-on-video v1.1.7)
after loading an AVI file got this stack trace : 

[ERROR] [09/28/2018 17:43:49.599] [gpv-akka.actor.default-dispatcher-3] [akka://gpv/user/playerController] got error decoding video in: /home/val/Videos/2017_bretagne_velo_PICT0003.AVI
java.lang.RuntimeException: got error decoding video in: /home/val/Videos/2017_bretagne_velo_PICT0003.AVI
	at peregin.gpv.video.SeekableVideoStream.readVideo(SeekableVideoStream.scala:85)
	at peregin.gpv.video.SeekableVideoStream.readPacket(SeekableVideoStream.scala:73)
	at peregin.gpv.video.SeekableVideoStream.readNextFrame(SeekableVideoStream.scala:114)
	at peregin.gpv.video.PlayerControllerActor$$anonfun$2.applyOrElse(SeekableVideoPlayer.scala:97)
	at peregin.gpv.video.PlayerControllerActor$$anonfun$2.applyOrElse(SeekableVideoPlayer.scala:89)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:684)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at peregin.gpv.video.PlayerControllerActor.akka$actor$LoggingFSM$$super$processEvent(SeekableVideoPlayer.scala:64)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at peregin.gpv.video.PlayerControllerActor.processEvent(SeekableVideoPlayer.scala:64)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:650)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at peregin.gpv.video.PlayerControllerActor.aroundReceive(SeekableVideoPlayer.scala:64)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[WARN] [09/28/2018 17:43:52.026] [gpv-akka.actor.default-dispatcher-3] [akka://gpv/user/playerController] unhandled Event(PauseCommand,ReadInProgress)
17:44:12.022 [gpv-akka.actor.default-dispatcher-3] INFO  p.gpv.video.SeekableVideoStream - see

**Comment by kvr000** [comment]
Please check the latest version, video engine has changed since then.
