### ISSUE TITLE
Missing dependency of the Github release library

### ISSUE THREAD

**Issue by aquarat** [peregin/gps-overlay-on-video#44]
This relates to the issue at ohnosequences/sbt-github-release/issues/28.

I tried installing the software on my desktop machine (Ubuntu 19.04 amd64, openjdk version "11.0.4" 2019-07-16). `sbt run` terminates, after downloading dependencies, with a complaint about a missing class (it was seemingly deprecated and then removed).

I got the software to work by commenting lines 56 to 73 inclusive in build.sbt and also commenting out line 27 in project/plugins.sbt.

Specifically removal of `addSbtPlugin("ohnosequences" % "sbt-github-release" % "0.7.0")` in plugins.sbt.

Below is the stacktrace from sbt run before the modifications. 

Great software, thanks :)

```

[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Loading settings for project root from build.sbt,version.sbt ...
[error] java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
[error] 	at ohnosequences.sbt.GithubRelease$defs$.ghreleaseMediaTypesMap(GithubRelease.scala:42)
[error] 	at ohnosequences.sbt.SbtGithubReleasePlugin$.$anonfun$projectSettings$9(SbtGithubReleasePlugin.scala:27)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:814)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:204)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.ClassNotFoundException: javax.activation.MimetypesFileTypeMap
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	at ohnosequences.sbt.GithubRelease$defs$.ghreleaseMediaTypesMap(GithubRelease.scala:42)
[error] 	at ohnosequences.sbt.SbtGithubReleasePlugin$.$anonfun$projectSettings$9(SbtGithubReleasePlugin.scala:27)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:814)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:204)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap

```

**Comment by peregin** [comment]
Thanks for the detailed bug report @aquarat !
I've added the explicit dependency for ```java.activation``` module to the plugins, since it was removed completely in java 11. The project still needs the ```sbt-github-release``` plugin to publish the artifacts to github.
Thanks for using the software!
