### ISSUE TITLE
Can't start app on mac os - module java.desktop does not "opens javax.swing.plaf.basic" to unnamed module

### ISSUE THREAD

**Issue by wojciechkoszyk** [peregin/gps-overlay-on-video#51]
Hello, I'm not really into java/scala but instructions were quite clear so I've tried. Unfortunately I can't make it starting. I had java installed before, I've installed sbt using brew and I downloaded `master` branch from github. Then just started using `sbt run` command. What I'm missing to make it working?

My env:
macOS 11.4, sbt 1.5.3, Java 16.0.1

Stack:
```[error] (run-main-0) java.lang.ExceptionInInitializerError
[error] java.lang.ExceptionInInitializerError
[error] 	at peregin.gpv.GpsOverlayApp.main(GpsOverlayApp.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean javax.swing.plaf.basic.BasicSliderUI.isDragging() accessible: module java.desktop does not "opens javax.swing.plaf.basic" to unnamed module @67b49a5d
[error] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[error] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[error] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[error] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[error] 	at peregin.gpv.gui.PercentageSlider.<init>(PercentageSlider.scala:39)
[error] 	at peregin.gpv.gui.VideoPanel.<init>(VideoPanel.scala:26)
[error] 	at peregin.gpv.GpsOverlayApp$$anon$1.<init>(GpsOverlayApp.scala:32)
[error] 	at peregin.gpv.GpsOverlayApp$.<clinit>(GpsOverlayApp.scala:32)
[error] 	at peregin.gpv.GpsOverlayApp.main(GpsOverlayApp.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)```

**Comment by peregin** [comment]
hey @wojciechkoszyk, did an update on the java options, please try it again with the latest version.
The issue happened as the code is uses reflection and in newer java versions (since 9 when the module system has been introduced) these calls are limited - are allowed only in certain conditions.
