### ISSUE TITLE
Unable to run on MacOS 12.3 (21E230) with openjdk version "17.0.2" 2022-01-18

### ISSUE THREAD

**Issue by leeeboo** [peregin/gps-overlay-on-video#87]
`07:39:56.138 [main] INFO  peregin.gpv.GpsOverlayApp$ - initializing...
Exception in thread "main" java.lang.ExceptionInInitializerError
	at peregin.gpv.GpsOverlayApp.main(GpsOverlayApp.scala)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean javax.swing.plaf.basic.BasicSliderUI.isDragging() accessible: module java.desktop does not "opens javax.swing.plaf.basic" to unnamed module @689eb690
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at peregin.gpv.gui.PercentageSlider.<init>(PercentageSlider.scala:37)
	at peregin.gpv.gui.VideoPanel.<init>(VideoPanel.scala:26)
	at peregin.gpv.GpsOverlayApp$$anon$1.<init>(GpsOverlayApp.scala:32)
	at peregin.gpv.GpsOverlayApp$.<clinit>(GpsOverlayApp.scala:32)
	... 1 more
`

Thanks!

**Comment by leeeboo** [comment]
resolved by:
java --add-opens java.desktop/javax.swing.plaf.basic=ALL-UNNAMED -jar  XXXX
